### ISSUE TITLE
How to set custom path for neovim config dir?

### ISSUE THREAD

**Issue by Mateiadrielrafael** [folke/neoconf.nvim#3]
I store my config in a different place and add it to the runtime path using vim.opt.runtimepath:append. Is there a way to tell this plugin my root directory is in some other place?

**Comment by folke** [comment]
No need for that. You can configure it in your `.neoconf.json` file in your custom config directory. See https://github.com/folke/neodev.nvim/blob/main/.neoconf.json for an example on how to do this

**Comment by folke** [comment]
Although, that might still give issues with your global neoconf file. Is that what you want to alter?

**Comment by Mateiadrielrafael** [comment]
@folke yep, that was my main issue. I ended up reworking my setup so I can simlink my config directory to the default location. It works as intended now.

**Comment by Mateiadrielrafael** [comment]
Should I close this?
