### ISSUE TITLE
bug: Windows global config file not recognized and Neoconf popup empty

### ISSUE THREAD

**Issue by burgr033** [folke/neoconf.nvim#33]
### Did you check docs and existing issues?

- [X] I have read all the neoconf.nvim docs
- [X] I have searched the existing issues of neoconf.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Windows 10 21H2

### Describe the bug

Global config files don't get recognized under Windows and the popup window for selecting / editing config files is empty

![image](https://github.com/folke/neoconf.nvim/assets/17072527/ef29fa8f-9d66-4154-985c-370fcb4e68be)

using local config files works (except they don't show up in the popup either)

### Steps To Reproduce

1. neovim on Windows (Config is under $ENV:LOCALAPPDATA\nvim)
2. open Neoconf (:Neoconf)
3. Window is empty

### Expected Behavior

Neoconf Popup should show either global or local config to edit

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
        vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
        "folke/tokyonight.nvim",
        "folke/neoconf.nvim",
        "neovim/nvim-lspconfig",
        -- add any other plugins here
}
require("lazy").setup(plugins, {
        root = root .. "/plugins",
})
require("neoconf").setup({})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by WillEhrendreich** [comment]
so it's not just me! lol.

**Comment by burgr033** [comment]
tested this morning, same behaviour
