### ISSUE TITLE
Question: how to use neoconf API to get self-defined configs/fields?

### ISSUE THREAD

**Issue by linrongbin16** [folke/neoconf.nvim#36]
Hi, I'm trying to understand the API doc: https://github.com/folke/neoconf.nvim#-api.

But still have some questions:
1. Where does the `Neoconf` defined? I copied the sample but my neovim reports: there's no `Neoconf` defined, it's `nil` value.
2. I add some configs to global `~/.config/nvim/neoconf.json` (see below), but cannot get it with API: `require('neoconf').get('myconfig.perf.file.maxsize')`, nvim reports the returned value is `nil`:
   ```json
   {
     "myconfig": {
       "perf.file.maxsize": 1024
     }
   }
   ```

**Comment by ogios** [comment]
maybe dot refers to object, better off with this? :
```json
{
  "myconfig": {
    "perf": {
      "file":{
        "maxsize": 1024
      }    
    }
  }
}
```

**Comment by linrongbin16** [comment]
thank you! @ogios  it solves my issue!
