### ISSUE TITLE
feature: Specify config path via environment variable

### ISSUE THREAD

**Issue by musjj** [folke/neoconf.nvim#42]
### Did you check the docs?

- [X] I have read all the neoconf.nvim docs

### Is your feature request related to a problem? Please describe.

Sometimes you want to generate project-specific configuration containing data that can't be statically baked. 

For example, with Nix you can create a shell environment that automatically pull dependencies for the project. But sometimes, you need to pass these dependencies to the LSP configuration. Since the data is dynamic and can't be known beforehand, you can't just hardcode it in a `.neoconf.json`

### Describe the solution you'd like

Being able to specify the absolute path to the config file via an env var (e.g. `NEOCONF_PATH`) will allow the user to dynamically generate a config file and pass the path to neoconf via the environment variable.

### Describe alternatives you've considered

The only other alternative is to manually create the config file and adjust them regularly.

**Comment by folke** [comment]
You can easily do this with a `.lazy.lua` file.
See [`opts.local_spec`](https://lazy.folke.io/configuration)
