### ISSUE TITLE
feature: field type has changed in lua_ls config

### ISSUE THREAD

**Issue by pysan3** [folke/neoconf.nvim#47]
### Did you check the docs?

- [X] I have read all the neoconf.nvim docs

### Is your feature request related to a problem? Please describe.

With a recent change in lua_ls (PRs listed below), the expected values for `workspace.checkThirdParty` has changed from a boolean to string enum.

Please update the schema to align with the latest changes.
Please see `# Describe the solution you'd like` section for the explanation of the new values.

- First change: https://github.com/LuaLS/lua-language-server/pull/2354
- Fix: https://github.com/LuaLS/lua-language-server/pull/2406

---

Sidenote:

Not related to the new schema but there seems to still be an issue with type conversion atm to keep backwards compatibility working.
 
- https://github.com/LuaLS/lua-language-server/issues/2407

### Describe the solution you'd like

Change schema for lua_ls.

---

> This lets you skip the "apply third party library to workspace configuration" prompt.
> 
> The value of Lua.workspace.checkThirdParty can now be one of:
> 
>     Ask (ask every time; this is equivalent to true)
>     Apply (always apply third-party libraries and set the workspace
>     configuration)
>     ApplyInMemory (always apply third-party libraries but don't set the
>     workspace configuration)
>     Disable (don't ask and don't apply; this is equivalent to false)
> 
> Backwards compatibility with the old boolean configuration values is maintained; true is treated as Ask and false is treated as Disable.

### Describe alternatives you've considered

None.

**Comment by pysan3** [comment]
Thanks to this PR, it is now not a breaking change but the values have been extended. https://github.com/LuaLS/lua-language-server/pull/2409

The values this option can take is as follows. 

- bool: true, false 
- string:
  - Ask (same as true)
  - Apply 
  - ApplyInMemory
  - Disable (same as false)

**Comment by pysan3** [comment]
Is there any reason why this is not merged?

**Comment by folke** [comment]
@pysan3 because this is not a PR?

Either way, the types are generated based on the schema provided by LuaLS
