### ISSUE TITLE
`null-ls` support

### ISSUE THREAD

**Issue by wizard-28** [folke/neoconf.nvim#5]
Are there any plans to support [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim)?

**Comment by folke** [comment]
What do you mean?

**Comment by c3n21** [comment]
It would be really useful to configure per project formatters, linters ecc... just in case somebody implements this would you accept a PR? @folke

**Comment by folke** [comment]
Sure!

**Comment by folke** [comment]
You can easily do this with a `.lazy.lua` file.
See [`opts.local_spec`](https://lazy.folke.io/configuration)
