### ISSUE TITLE
bug: Setup `require("neoconf").setup()` should be run **BEFORE** BUG  

### ISSUE THREAD

**Issue by leoatchina** [folke/neoconf.nvim#58]
### Did you check docs and existing issues?

- [X] I have read all the neoconf.nvim docs
- [X] I have searched the existing issues of neoconf.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10 (nvim-qt and neovide)

### Operating system/version

WIndow10/11

### Describe the bug

My (neo)vim's config is set up aiming to compatible for both neovim and vim in LINUX/MACOS/WINDOWS,  so  I have to use `vim-plug` to setting up my config ,  and `:luafile` is occupied to load pure lua plugins.  
I have run into such a strange bug  with neovim with `gui`, in other words `nvim-qt` and `neovide`.
In my config  `neoconf` is definitely set up before  `mason-lspconfig`.In other OS or  neovim without gui in windows,   the waring 
`NOT` raised up when I start neovim ,   I only appear in  windows when I use neovide or nvim-qt.
https://github.com/leoatchina/leovim/blob/master/conf.d/element/lua/lsp.lua

I think it must be the `lsputil` check bug.
https://github.com/folke/neoconf.nvim/blob/f1fd38d61d11f3b1b3e7dc75dc667f79cf2fa58b/lua/neoconf/health.lua#L72-L78

### Steps To Reproduce

WINDOWS-> vim-plug-> neovide or nvim-qt

### Expected Behavior

No, warning

### Repro

https://github.com/leoatchina/leovim/blob/master/conf.d/element/lua/lsp.lua

**Comment by jgoguen** [comment]
I'm seeing this on Fedora 40, CLI `nvim`, using lazy.nvim as the config base. The only customization I'm doing around neoconf is setting `import.vscode = false`:

```lua
-- ~/.config/nvim/lua/plugins/neoconf.lua
 local M = {
    'folke/neoconf.nvim',
    opts = {
        import = {
            vscode = false,
        },
    },
}

return M
```

And I'm loading plugin configs using lazy's `spec` parameter:

```lua
-- ~/.config/nvim/lua/config/lazy.lua

require('lazy').setup({
    spec = {
        { 'LazyVim/LazyVim', import = 'lazyvim.plugins' },
        { import = 'plugins' },
    },
})
```

My full neovim config, if needed, is at https://github.com/jgoguen/dotfiles/tree/main/dot_config/exact_nvim/exact_lua (managed by chezmoi, the `exact_` prefix on a directory name tells chezmoi to remove any files it doesn't know about in that directory).
