### ISSUE TITLE
feature: Run own callback?

### ISSUE THREAD

**Issue by Ajaymamtora** [folke/neoconf.nvim#65]
### Did you check the docs?

- [X] I have read all the neoconf.nvim docs

### Is your feature request related to a problem? Please describe.

I want to re-call telescope setup with the user config when it changes.

### Describe the solution you'd like

Expose a an autocmd or something I could use as a hook to call my own function when the neoconf settings change

### Describe alternatives you've considered

none

**Comment by folke** [comment]
What does this have to do with telescope?
